version: "3.9"

services:
    postgres:
        image: pgvector/pgvector:pg16
        container_name: postgres
        environment:
            POSTGRES_DB: pluto_interview
            POSTGRES_USER: pluto
            POSTGRES_PASSWORD: Chen@0216
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U pluto -d pluto_interview"]
            interval: 5s
            timeout: 3s
            retries: 20
    
    redis:
        image: redis:8.4
        container_name: redis
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 5s
            timeout: 3s
            retries: 20

volumes:
    postgres_data:
    redis_data: