spring:
    datasource:
        url: ${PLUTO_INTERVIEW_DB_URL}
        username: ${POSTGRES_USERNAME}
        password: ${POSTGRES_PASSWORD}
    redis:
        host: ${spring.redis.host:localhost}
        port: ${spring.redis.port:6379}
        database: ${spring.redis.database:0}
    mvc:
        concurrency:
            response-handling:
                enabled: true
    jpa:
        hibernate:
            ddl-auto: validate

langchain4j:
    community:
        dashscope:
            chat-model:
                api-key: ${DASHSCOPE_API_KEY}
                model-name: qwen-plus
            streaming-chat-model:
                api-key: ${DASHSCOPE_API_KEY}
                model-name: qwen-plus
            embedding-model:
                api-key: ${DASHSCOPE_API_KEY}
                model-name: text-embedding-v4

thread-pool:
    core-pool-size: 8
    max-pool-size: 16
    queue-capacity: 100
    keep-alive-seconds: 120

jwt:
    secret: ${PLUTO_INTERVIEW_JWT_SECRET}
    issuer: Pluto Interview
    refreshTokenTtl: 7d
            
service:
    auth:
        timeout: 5s
        
pgvector:
    host: localhost
    port: 5432
    user: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    database: pluto_interview
    table: interview_question_embeddings
    
app:
    cors:
        allowed-origins: "http://interview.pluto.com"
        
#security:
#    cors:
#        allowed-origins: "*"

rate-limiting:
    capacity: 100
    refill-amount: 100
    refill-period: 1m