---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by pluto.
--- DateTime: 16/1/2026 9:18 pm
---
local token_key = KEYS[1]
local refresh_token_key = KEYS[2]

redis.call("DEL", token_key)
redis.call("DEL", refresh_token_key)