---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by pluto.
--- DateTime: 17/1/2026 10:55 pm
---
local key = KEYS[1]
local idKey = ARGV[1]
local id = ARGV[2]
local emailKey = ARGV[3]
local email = ARGV[4]
local usernameKey = ARGV[5]
local username = ARGV[6]
local preferredQuestionTypesKey = ARGV[7]
local preferredQuestionTypes = ARGV[8]
local preferredDifficultyLevelKey = ARGV[9]
local preferredDifficultyLevel = ARGV[10]
local ttl = tonumber(ARGV[11])

redis.call("HMSET", key, idKey, id, emailKey, email, usernameKey, username,
    preferredQuestionTypesKey, preferredQuestionTypes, preferredDifficultyLevelKey, preferredDifficultyLevel)
redis.call("EXPIRE", key, ttl)