---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by pluto.
--- DateTime: 16/1/2026 9:39 pm
---
local token_key = KEYS[1]
local refresh_token_key = KEYS[2]
local token_value = ARGV[1]
local token_ttl = tonumber(ARGV[2])
local refresh_token_value = ARGV[3]
local refresh_token_ttl = tonumber(ARGV[4])

redis.call("SET", token_key, token_value)
redis.call("EXPIRE", token_key, token_ttl)
redis.call("SET", refresh_token_key, refresh_token_value)
redis.call("EXPIRE", refresh_token_key, refresh_token_ttl)